//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedCenterEntities : DbContext
    {
        public MedCenterEntities()
            : base("name=MedCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Врач> Врач { get; set; }
        public virtual DbSet<Запись> Запись { get; set; }
        public virtual DbSet<Зуб> Зуб { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Лечение> Лечение { get; set; }
        public virtual DbSet<Прием> Прием { get; set; }
        public virtual DbSet<Услуга> Услуга { get; set; }
    }
}
