//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись
    {
        public int НомерЗаписи { get; set; }
        public int ID_Клиента { get; set; }
        public int ID_Врача { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual Врач Врач { get; set; }
        public virtual Клиент Клиент { get; set; }
    }
}
